def inform_about_the_result(times):
    print(f"Your number was drawn after {times} time(s).")

def inform_about_the_result():
    raise Exception